apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: clea1jz0m-nodejs 
  janus-idp.io/tekton: clea1jz0m-nodejs
  backstage.io/kubernetes-id: clea1jz0m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clea1jz0m-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml