apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: clea1jz0m-nodejs-gitops
  description: This is GitOps manifest for clea1jz0m-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=clea1jz0m-nodejs
    backstage.io/kubernetes-id: clea1jz0m-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: clea1jz0m-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:clea1jz0m-nodejs
